# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'xenon'
variables:
  imageName: 'your-container-image-name:$(build.buildId)'
steps:
#- script: docker build -f Dockerfile -t $(imageName) .
#  displayName: 'docker build'
- task: Docker@1
  inputs:
    dockerFile: SmartHotel360.PublicWeb/Dockerfile
    useDefaultContext: false
    buildContext: SmartHotel360.PublicWeb
    imageName: '$(Build.Repository.Name):$(Build.BuildId)'
    qualifyImageName: false
- task: Docker@1
  inputs:
    azureSubscriptionEndpoint: RMPM
    azureContainerRegistry: ronacr.azurecr.io
    command: 'Push an image'
    imageName: '$(Build.Repository.Name):$(Build.BuildId)'
    qualifyImageName: false
