# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  AgentOS: Ubuntu
  version: '16.04'
  poolName: $(AgentOS)-$(version)
  
stages:
- stage: Build
  jobs:
  - job: Build
    displayName: My First Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo my first Build job


- stage: production
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    pool:
      vmImage: 'Ubuntu-16.04'
    displayName: deploy Web App
    environment: 'smarthotel-prod'   # creates an environment if it doesn’t exist
    strategy: 
      runOnce:
        deploy:                     # records deployments against ‘smarthotel-dev’
          steps:
          - script: echo deploy to preprod
          - script: echo run tests
